name: pick_pay
description: "Pick Pay - A modern payment solution"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^5.6.2
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/icons/
    - assets/logos/
    - assets/animations/
    - assets/audios/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Amiri-Italic.ttf
          weight: 400
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
    - family: ArabQuranIslamic
      fonts:
        - asset: assets/fonts/ArabQuranIslamic-Italic.ttf
          weight: 400
        - asset: assets/fonts/ArabQuranIslamic-Regular.ttf
          weight: 400
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        